name: video_feed
description: The autoplay videos in feed.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  video_player: ^0.10.2+5
  stream_channel: ">=1.6.0 <=2.0.0"
  built_redux: ^7.4.5
  built_value: ^6.3.1
  built_collection: ^4.1.0
  flutter_built_redux: ^0.6.0
  inview_notifier_list: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.2.8
  built_value_generator: ^6.1.0

flutter:
  uses-material-design: true