name: video_feed
description: The autoplay videos in feed.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  built_redux: ^7.5.6
  video_player: ^0.10.2+5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true